{
   "overflow" : false,
   "action" : null,
   "job" : null,
   "type" : "ListResult",
   "status" : "OK",
   "total" : 18,
   "result" : [
      {
         "container" : "ORACLE_DB_CONTAINER-137",
         "compressedLinkingEnabled" : false,
         "filesPerSet" : 5,
         "restoration" : false,
         "externalFilePath" : null,
         "rmanChannels" : 2,
         "runtime" : {
            "racEnabled" : null,
            "dnfsEnabled" : false,
            "lastNonLoggedLocation" : null,
            "databaseStats" : [],
            "activeInstances" : [],
            "databaseRole" : null,
            "databaseMode" : null,
            "bctEnabled" : false,
            "enabled" : "ENABLED",
            "accessible" : false,
            "status" : "UNKNOWN",
            "notAccessibleReason" : "Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection",
            "archivelogEnabled" : null,
            "databaseSize" : 0,
            "type" : "OracleSourceRuntime"
         },
         "operations" : {
            "postSync" : [],
            "type" : "LinkedSourceOperations",
            "preSync" : []
         },
         "config" : "ORACLE_SINGLE_CONFIG-53",
         "backupLevelEnabled" : false,
         "type" : "OracleLinkedSource",
         "virtual" : false,
         "bandwidthLimit" : 0,
         "description" : null,
         "status" : "DEFAULT",
         "encryptedLinkingEnabled" : false,
         "checkLogical" : false,
         "staging" : false,
         "reference" : "ORACLE_LINKED_SOURCE-31",
         "name" : "singpdb",
         "numberOfConnections" : 1,
         "linked" : true,
         "namespace" : null
      },
      {
         "encryptedLinkingEnabled" : false,
         "checkLogical" : false,
         "staging" : false,
         "name" : "PDB",
         "reference" : "ORACLE_LINKED_SOURCE-32",
         "numberOfConnections" : 1,
         "namespace" : null,
         "linked" : true,
         "container" : "ORACLE_DB_CONTAINER-138",
         "externalFilePath" : "",
         "restoration" : false,
         "filesPerSet" : 5,
         "compressedLinkingEnabled" : true,
         "operations" : {
            "type" : "LinkedSourceOperations",
            "postSync" : [],
            "preSync" : []
         },
         "runtime" : {
            "lastNonLoggedLocation" : null,
            "status" : "UNKNOWN",
            "enabled" : "DISABLED",
            "accessible" : false,
            "databaseStats" : [],
            "activeInstances" : [],
            "databaseRole" : null,
            "databaseMode" : null,
            "type" : "OraclePDBSourceRuntime",
            "databaseSize" : 0,
            "notAccessibleReason" : "Object is not available for monitoring"
         },
         "rmanChannels" : 2,
         "backupLevelEnabled" : false,
         "config" : "ORACLE_PDB_CONFIG-54",
         "virtual" : false,
         "type" : "OracleLinkedSource",
         "bandwidthLimit" : 0,
         "status" : "DEFAULT",
         "description" : null
      },
      {
         "restoration" : false,
         "externalFilePath" : "",
         "compressedLinkingEnabled" : true,
         "filesPerSet" : 5,
         "operations" : {
            "preSync" : [],
            "postSync" : [],
            "type" : "LinkedSourceOperations"
         },
         "runtime" : {
            "status" : "UNKNOWN",
            "bctEnabled" : false,
            "enabled" : "ENABLED",
            "accessible" : false,
            "databaseStats" : [],
            "activeInstances" : [],
            "databaseMode" : null,
            "databaseRole" : null,
            "type" : "OracleSourceRuntime",
            "databaseSize" : 0,
            "archivelogEnabled" : null,
            "notAccessibleReason" : "Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection",
            "racEnabled" : null,
            "lastNonLoggedLocation" : null,
            "dnfsEnabled" : false
         },
         "rmanChannels" : 2,
         "container" : "ORACLE_DB_CONTAINER-29",
         "bandwidthLimit" : 0,
         "description" : null,
         "status" : "DEFAULT",
         "backupLevelEnabled" : false,
         "config" : "ORACLE_RAC_CONFIG-10",
         "type" : "OracleLinkedSource",
         "virtual" : false,
         "checkLogical" : false,
         "staging" : false,
         "encryptedLinkingEnabled" : false,
         "namespace" : null,
         "linked" : true,
         "name" : "racdba",
         "reference" : "ORACLE_LINKED_SOURCE-5",
         "numberOfConnections" : 1
      },
      {
         "description" : null,
         "status" : "DEFAULT",
         "bandwidthLimit" : 0,
         "virtual" : false,
         "type" : "OracleLinkedSource",
         "config" : "ORACLE_SINGLE_CONFIG-56",
         "backupLevelEnabled" : false,
         "rmanChannels" : 2,
         "runtime" : {
            "dnfsEnabled" : false,
            "lastNonLoggedLocation" : null,
            "racEnabled" : null,
            "archivelogEnabled" : null,
            "type" : "OracleSourceRuntime",
            "databaseSize" : 0,
            "notAccessibleReason" : "Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection",
            "accessible" : false,
            "bctEnabled" : false,
            "enabled" : "ENABLED",
            "status" : "UNKNOWN",
            "databaseStats" : [],
            "databaseMode" : null,
            "activeInstances" : [],
            "databaseRole" : null
         },
         "operations" : {
            "postSync" : [],
            "type" : "LinkedSourceOperations",
            "preSync" : []
         },
         "filesPerSet" : 5,
         "compressedLinkingEnabled" : false,
         "externalFilePath" : null,
         "restoration" : false,
         "container" : "ORACLE_DB_CONTAINER-209",
         "linked" : true,
         "namespace" : null,
         "numberOfConnections" : 1,
         "reference" : "ORACLE_LINKED_SOURCE-42",
         "name" : "targetcon",
         "staging" : false,
         "checkLogical" : false,
         "encryptedLinkingEnabled" : false
      },
      {
         "compressedLinkingEnabled" : true,
         "filesPerSet" : 5,
         "restoration" : false,
         "externalFilePath" : null,
         "rmanChannels" : 2,
         "runtime" : {
            "racEnabled" : null,
            "lastNonLoggedLocation" : null,
            "dnfsEnabled" : false,
            "databaseStats" : [],
            "activeInstances" : [],
            "databaseMode" : null,
            "databaseRole" : null,
            "status" : "UNKNOWN",
            "bctEnabled" : false,
            "accessible" : false,
            "enabled" : "ENABLED",
            "notAccessibleReason" : "Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection",
            "databaseSize" : 0,
            "type" : "OracleSourceRuntime",
            "archivelogEnabled" : null
         },
         "operations" : {
            "type" : "LinkedSourceOperations",
            "postSync" : [],
            "preSync" : []
         },
         "container" : "ORACLE_DB_CONTAINER-223",
         "bandwidthLimit" : 0,
         "status" : "DEFAULT",
         "description" : null,
         "config" : "ORACLE_SINGLE_CONFIG-38",
         "backupLevelEnabled" : false,
         "type" : "OracleLinkedSource",
         "virtual" : false,
         "checkLogical" : false,
         "staging" : false,
         "encryptedLinkingEnabled" : false,
         "linked" : true,
         "namespace" : null,
         "reference" : "ORACLE_LINKED_SOURCE-46",
         "name" : "orcl",
         "numberOfConnections" : 1
      },
      {
         "allowAutoVDBRestartOnHostReboot" : false,
         "redoLogGroups" : 3,
         "container" : "ORACLE_DB_CONTAINER-229",
         "restoration" : false,
         "nodeListenerList" : [],
         "operations" : {
            "postRefresh" : [],
            "preSnapshot" : [],
            "type" : "VirtualSourceOperations",
            "preStop" : [],
            "postRollback" : [],
            "preRollback" : [],
            "preStart" : [],
            "preRefresh" : [],
            "postStart" : [],
            "postStop" : [],
            "configureClone" : [],
            "postSnapshot" : []
         },
         "runtime" : {
            "racEnabled" : null,
            "dnfsEnabled" : false,
            "lastNonLoggedLocation" : null,
            "bctEnabled" : false,
            "enabled" : "ENABLED",
            "accessible" : false,
            "status" : "UNKNOWN",
            "databaseMode" : null,
            "databaseStats" : [],
            "activeInstances" : [],
            "databaseRole" : null,
            "archivelogEnabled" : null,
            "databaseSize" : 0,
            "type" : "OracleSourceRuntime",
            "notAccessibleReason" : "Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection"
         },
         "configParams" : {
            "_omf" : "'ENABLED'",
            "audit_sys_operations" : "FALSE",
            "remote_login_passwordfile" : "'EXCLUSIVE'",
            "memory_target" : "792723456",
            "compatible" : "'12.1.0.2.0'",
            "log_archive_dest_1" : "'location=/mnt/provision/siclone/archive/ MANDATORY'",
            "filesystemio_options" : "'setall'",
            "open_cursors" : "300",
            "audit_trail" : "'NONE'",
            "processes" : "500"
         },
         "config" : "ORACLE_SINGLE_CONFIG-87",
         "type" : "OracleVirtualSource",
         "virtual" : true,
         "status" : "DEFAULT",
         "manualProvisioning" : null,
         "description" : null,
         "fileMappingRules" : null,
         "staging" : false,
         "mountBase" : "/mnt/provision",
         "archivelogMode" : true,
         "name" : "siclone",
         "reference" : "ORACLE_VIRTUAL_SOURCE-64",
         "customEnvVars" : [],
         "namespace" : null,
         "configTemplate" : null,
         "redoLogSizeInMB" : 100,
         "linked" : false
      },
      {
         "staging" : false,
         "mountBase" : "/mnt/provision",
         "fileMappingRules" : null,
         "reference" : "ORACLE_VIRTUAL_SOURCE-56",
         "name" : "vPDBtest",
         "archivelogMode" : true,
         "customEnvVars" : [],
         "redoLogSizeInMB" : 100,
         "linked" : false,
         "configTemplate" : null,
         "namespace" : null,
         "allowAutoVDBRestartOnHostReboot" : false,
         "container" : "ORACLE_DB_CONTAINER-207",
         "redoLogGroups" : 3,
         "nodeListenerList" : [],
         "restoration" : false,
         "configParams" : {
            "diagnostic_dest" : "'/u01/app/oracle'",
            "compatible" : "'12.1.0.2.0'",
            "db_domain" : "''",
            "remote_login_passwordfile" : "'EXCLUSIVE'",
            "dispatchers" : "'(PROTOCOL=TCP) (SERVICE=targetconXDB)'",
            "audit_file_dest" : "'/u01/app/oracle/admin/targetcon/adump'",
            "processes" : "300",
            "audit_trail" : "'DB'",
            "open_cursors" : "300",
            "enable_pluggable_database" : "TRUE",
            "pga_aggregate_target" : "398458880",
            "sga_target" : "1207959552"
         },
         "runtime" : {
            "lastNonLoggedLocation" : null,
            "databaseSize" : 0,
            "type" : "OraclePDBSourceRuntime",
            "notAccessibleReason" : "Object is not available for monitoring",
            "status" : "UNKNOWN",
            "accessible" : false,
            "enabled" : "DISABLED",
            "databaseStats" : [],
            "databaseRole" : null,
            "activeInstances" : [],
            "databaseMode" : null
         },
         "operations" : {
            "type" : "VirtualSourceOperations",
            "preSnapshot" : [],
            "postRefresh" : [],
            "preStop" : [],
            "postRollback" : [],
            "preRollback" : [],
            "preStart" : [],
            "postStop" : [],
            "preRefresh" : [],
            "postStart" : [],
            "postSnapshot" : [],
            "configureClone" : []
         },
         "config" : "ORACLE_PDB_CONFIG-79",
         "virtual" : true,
         "type" : "OracleVirtualSource",
         "manualProvisioning" : null,
         "status" : "DEFAULT",
         "description" : null
      },
      {
         "configTemplate" : null,
         "namespace" : null,
         "linked" : false,
         "redoLogSizeInMB" : 100,
         "name" : "VOracledsource_F0C",
         "archivelogMode" : true,
         "reference" : "ORACLE_VIRTUAL_SOURCE-80",
         "customEnvVars" : [],
         "fileMappingRules" : null,
         "staging" : false,
         "mountBase" : "/mnt/provision",
         "description" : null,
         "manualProvisioning" : null,
         "status" : "DEFAULT",
         "config" : "ORACLE_SINGLE_CONFIG-103",
         "type" : "OracleVirtualSource",
         "virtual" : true,
         "restoration" : false,
         "nodeListenerList" : [],
         "operations" : {
            "postSnapshot" : [],
            "configureClone" : [],
            "postStop" : [],
            "preRefresh" : [],
            "postStart" : [],
            "preStop" : [],
            "type" : "VirtualSourceOperations",
            "postRefresh" : [],
            "preSnapshot" : [],
            "preRollback" : [],
            "preStart" : [],
            "postRollback" : []
         },
         "runtime" : {
            "racEnabled" : null,
            "lastNonLoggedLocation" : null,
            "dnfsEnabled" : false,
            "activeInstances" : [],
            "databaseStats" : [],
            "databaseMode" : null,
            "databaseRole" : null,
            "status" : "FAILED",
            "accessible" : false,
            "bctEnabled" : false,
            "enabled" : "ENABLED",
            "notAccessibleReason" : "Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection",
            "databaseSize" : 0,
            "type" : "OracleSourceRuntime",
            "archivelogEnabled" : null
         },
         "configParams" : {
            "processes" : "700",
            "open_cursors" : "300",
            "audit_trail" : "'NONE'",
            "sga_target" : "738197504",
            "pga_aggregate_target" : "245366784",
            "log_archive_dest_1" : "'location=/mnt/provision/VOracledsource_F0C/archive/ MANDATORY'",
            "filesystemio_options" : "'setall'",
            "compatible" : "'11.2.0.4.0'",
            "remote_login_passwordfile" : "'EXCLUSIVE'",
            "_omf" : "'ENABLED'",
            "audit_sys_operations" : "FALSE"
         },
         "allowAutoVDBRestartOnHostReboot" : false,
         "redoLogGroups" : 3,
         "container" : "ORACLE_DB_CONTAINER-245"
      },
      {
         "restoration" : false,
         "nodeListenerList" : [],
         "operations" : {
            "postSnapshot" : [],
            "configureClone" : [],
            "postStop" : [],
            "postStart" : [],
            "preRefresh" : [],
            "preStop" : [],
            "type" : "VirtualSourceOperations",
            "preSnapshot" : [],
            "postRefresh" : [],
            "preRollback" : [],
            "preStart" : [],
            "postRollback" : []
         },
         "runtime" : {
            "racEnabled" : null,
            "lastNonLoggedLocation" : null,
            "dnfsEnabled" : false,
            "status" : "UNKNOWN",
            "bctEnabled" : false,
            "enabled" : "ENABLED",
            "accessible" : false,
            "activeInstances" : [],
            "databaseStats" : [],
            "databaseRole" : null,
            "databaseMode" : null,
            "type" : "OracleSourceRuntime",
            "databaseSize" : 0,
            "archivelogEnabled" : null,
            "notAccessibleReason" : "Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection"
         },
         "configParams" : {
            "compatible" : "'12.1.0.2.0'",
            "memory_target" : "792723456",
            "remote_login_passwordfile" : "'EXCLUSIVE'",
            "audit_sys_operations" : "FALSE",
            "_omf" : "'ENABLED'",
            "processes" : "500",
            "open_cursors" : "300",
            "audit_trail" : "'NONE'",
            "log_archive_dest_1" : "'location=/mnt/provision/si4rac/archive/ MANDATORY'",
            "filesystemio_options" : "'setall'"
         },
         "allowAutoVDBRestartOnHostReboot" : true,
         "redoLogGroups" : 3,
         "container" : "ORACLE_DB_CONTAINER-210",
         "manualProvisioning" : null,
         "description" : null,
         "status" : "DEFAULT",
         "config" : "ORACLE_SINGLE_CONFIG-81",
         "type" : "OracleVirtualSource",
         "virtual" : true,
         "fileMappingRules" : null,
         "staging" : false,
         "mountBase" : "/mnt/provision",
         "namespace" : null,
         "configTemplate" : null,
         "linked" : false,
         "redoLogSizeInMB" : 100,
         "name" : "si4rac",
         "archivelogMode" : true,
         "reference" : "ORACLE_VIRTUAL_SOURCE-58",
         "customEnvVars" : []
      },
      {
         "type" : "MSSqlLinkedSource",
         "virtual" : false,
         "backupLocationCredentials" : null,
         "config" : "MSSQL_SINGLE_CONFIG-23",
         "description" : null,
         "status" : "DEFAULT",
         "backupLocationUser" : null,
         "container" : "MSSQL_DB_CONTAINER-171",
         "operations" : {
            "postSync" : [],
            "type" : "LinkedSourceOperations",
            "preSync" : []
         },
         "runtime" : {
            "enabled" : "DISABLED",
            "accessible" : false,
            "status" : "UNKNOWN",
            "notAccessibleReason" : "Object is not available for monitoring",
            "databaseSize" : 0,
            "type" : "MSSqlSourceRuntime"
         },
         "sharedBackupLocation" : "\\\\172.16.180.133\\backups",
         "restoration" : false,
         "externalFilePath" : null,
         "reference" : "MSSQL_LINKED_SOURCE-14",
         "encryptionKey" : null,
         "name" : "AdventureWorksLT2008R2",
         "linked" : true,
         "namespace" : null,
         "validatedSyncMode" : "TRANSACTION_LOG",
         "stagingSource" : "MSSQL_STAGING_SOURCE-14",
         "staging" : false
      },
      {
         "preScript" : null,
         "fileMappingRules" : null,
         "staging" : false,
         "mountBase" : "C:\\Program Files\\Delphix\\DelphixConnector\\564d870b-e091-7339-5d98-e7cc4bdbfbcc-vdb-11",
         "namespace" : null,
         "linked" : false,
         "name" : "mstest_lsn",
         "reference" : "MSSQL_VIRTUAL_SOURCE-11",
         "restoration" : false,
         "operations" : {
            "postRollback" : [],
            "preRollback" : [],
            "preStart" : [],
            "type" : "VirtualSourceOperations",
            "preSnapshot" : [],
            "postRefresh" : [],
            "preStop" : [],
            "postStop" : [],
            "postStart" : [],
            "preRefresh" : [],
            "postSnapshot" : [],
            "configureClone" : []
         },
         "runtime" : {
            "databaseSize" : 0,
            "type" : "MSSqlSourceRuntime",
            "notAccessibleReason" : "Failed to connect to host 172.16.180.132 [172.16.180.132]",
            "status" : "UNKNOWN",
            "enabled" : "ENABLED",
            "accessible" : false
         },
         "configParams" : null,
         "allowAutoVDBRestartOnHostReboot" : true,
         "container" : "MSSQL_DB_CONTAINER-175",
         "description" : null,
         "status" : "DEFAULT",
         "config" : "MSSQL_SINGLE_CONFIG-36",
         "virtual" : true,
         "type" : "MSSqlVirtualSource",
         "postScript" : null
      },
      {
         "namespace" : null,
         "linked" : false,
         "name" : "mstest_time",
         "reference" : "MSSQL_VIRTUAL_SOURCE-9",
         "preScript" : null,
         "fileMappingRules" : null,
         "staging" : false,
         "mountBase" : "C:\\Program Files\\Delphix\\DelphixConnector\\564d870b-e091-7339-5d98-e7cc4bdbfbcc-vdb-9",
         "description" : null,
         "status" : "DEFAULT",
         "config" : "MSSQL_SINGLE_CONFIG-34",
         "virtual" : true,
         "type" : "MSSqlVirtualSource",
         "postScript" : null,
         "restoration" : false,
         "operations" : {
            "postSnapshot" : [],
            "configureClone" : [],
            "postStop" : [],
            "preRefresh" : [],
            "postStart" : [],
            "preStop" : [],
            "type" : "VirtualSourceOperations",
            "preSnapshot" : [],
            "postRefresh" : [],
            "preStart" : [],
            "preRollback" : [],
            "postRollback" : []
         },
         "runtime" : {
            "status" : "UNKNOWN",
            "accessible" : false,
            "enabled" : "DISABLED",
            "notAccessibleReason" : "Object is not available for monitoring",
            "type" : "MSSqlSourceRuntime",
            "databaseSize" : 0
         },
         "configParams" : null,
         "allowAutoVDBRestartOnHostReboot" : true,
         "container" : "MSSQL_DB_CONTAINER-173"
      },
      {
         "container" : "MSSQL_DB_CONTAINER-171",
         "runtime" : {
            "notAccessibleReason" : "Object is not available for monitoring",
            "type" : "MSSqlSourceRuntime",
            "databaseSize" : 0,
            "enabled" : "DISABLED",
            "accessible" : false,
            "status" : "UNKNOWN"
         },
         "restoration" : false,
         "postScript" : null,
         "type" : "MSSqlStagingSource",
         "virtual" : false,
         "config" : "MSSQL_SINGLE_CONFIG-32",
         "status" : "DEFAULT",
         "description" : null,
         "mountBase" : "C:\\Program Files\\Delphix\\DelphixConnector\\564d870b-e091-7339-5d98-e7cc4bdbfbcc-staging-171",
         "staging" : true,
         "preScript" : null,
         "reference" : "MSSQL_STAGING_SOURCE-14",
         "name" : "564d870b-e091-7339-5d98-e7cc4bdbfbcc-staging-171",
         "linked" : false,
         "namespace" : null
      },
      {
         "restoration" : false,
         "operations" : {
            "preSync" : [],
            "postSync" : [],
            "type" : "LinkedSourceOperations"
         },
         "runtime" : {
            "status" : "RUNNING",
            "enabled" : "ENABLED",
            "accessible" : true,
            "notAccessibleReason" : null,
            "type" : "AppDataSourceRuntime",
            "databaseSize" : 25594880
         },
         "container" : "APPDATA_CONTAINER-146",
         "followSymlinks" : [],
         "status" : "DEFAULT",
         "description" : null,
         "config" : "APPDATA_SOURCE_CONFIG-16",
         "virtual" : false,
         "type" : "AppDataLinkedDirectSource",
         "parameters" : {},
         "staging" : false,
         "linked" : true,
         "excludes" : [],
         "namespace" : null,
         "reference" : "APPDATA_LINKED_SOURCE-7",
         "name" : "TESTEBI"
      },
      {
         "linked" : false,
         "namespace" : null,
         "reference" : "APPDATA_VIRTUAL_SOURCE-6",
         "name" : "autofs",
         "parameters" : {},
         "additionalMountPoints" : [],
         "staging" : false,
         "status" : "DEFAULT",
         "description" : null,
         "config" : "APPDATA_SOURCE_CONFIG-19",
         "virtual" : true,
         "type" : "AppDataVirtualSource",
         "restoration" : false,
         "operations" : {
            "preStart" : [],
            "preRollback" : [],
            "postRollback" : [],
            "preStop" : [],
            "type" : "VirtualSourceOperations",
            "preSnapshot" : [],
            "postRefresh" : [],
            "postSnapshot" : [],
            "configureClone" : [],
            "postStop" : [],
            "postStart" : [],
            "preRefresh" : []
         },
         "runtime" : {
            "status" : "UNKNOWN",
            "accessible" : true,
            "enabled" : "DISABLED",
            "notAccessibleReason" : null,
            "type" : "AppDataSourceRuntime",
            "databaseSize" : 25594880
         },
         "allowAutoVDBRestartOnHostReboot" : false,
         "container" : "APPDATA_CONTAINER-149"
      },
      {
         "stagingSource" : "ASE_STAGING_SOURCE-60",
         "staging" : false,
         "loadBackupPath" : "/u02/sybase_back",
         "name" : "Sybase dsource",
         "dumpCredentials" : null,
         "reference" : "ASE_LINKED_SOURCE-60",
         "namespace" : null,
         "validatedSyncMode" : "ENABLED",
         "linked" : true,
         "container" : "ASE_DB_CONTAINER-227",
         "runtime" : {
            "truncateLogOnCheckpoint" : null,
            "status" : "UNKNOWN",
            "durabilityLevel" : null,
            "accessible" : false,
            "enabled" : "ENABLED",
            "notAccessibleReason" : "Execution thread unexpectedly failed",
            "databaseSize" : 0,
            "type" : "ASESourceRuntime"
         },
         "operations" : {
            "postSync" : [],
            "type" : "LinkedSourceOperations",
            "preSync" : []
         },
         "externalFilePath" : null,
         "restoration" : false,
         "loadLocation" : null,
         "type" : "ASELinkedSource",
         "virtual" : false,
         "config" : "ASE_SI_CONFIG-64",
         "description" : null,
         "status" : "DEFAULT"
      },
      {
         "reference" : "ASE_VIRTUAL_SOURCE-40",
         "name" : "autotest",
         "linked" : false,
         "namespace" : null,
         "mountBase" : "/u01/app/toolkit/564d870b-e091-7339-5d98-e7cc4bdbfbcc-vdb-40",
         "staging" : false,
         "fileMappingRules" : null,
         "config" : "ASE_SI_CONFIG-110",
         "type" : "ASEVirtualSource",
         "virtual" : true,
         "description" : null,
         "status" : "DEFAULT",
         "allowAutoVDBRestartOnHostReboot" : false,
         "container" : "ASE_DB_CONTAINER-228",
         "restoration" : false,
         "configParams" : null,
         "runtime" : {
            "accessible" : false,
            "durabilityLevel" : null,
            "enabled" : "ENABLED",
            "status" : "UNKNOWN",
            "notAccessibleReason" : "Execution thread unexpectedly failed",
            "databaseSize" : 0,
            "type" : "ASESourceRuntime",
            "truncateLogOnCheckpoint" : null
         },
         "operations" : {
            "preRefresh" : [],
            "postStart" : [],
            "postStop" : [],
            "configureClone" : [],
            "postSnapshot" : [],
            "preSnapshot" : [],
            "postRefresh" : [],
            "type" : "VirtualSourceOperations",
            "preStop" : [],
            "postRollback" : [],
            "preRollback" : [],
            "preStart" : []
         }
      },
      {
         "container" : "ASE_DB_CONTAINER-227",
         "runtime" : {
            "truncateLogOnCheckpoint" : null,
            "status" : "UNKNOWN",
            "durabilityLevel" : null,
            "enabled" : "ENABLED",
            "accessible" : false,
            "type" : "ASESourceRuntime",
            "databaseSize" : 0,
            "notAccessibleReason" : "Execution thread unexpectedly failed"
         },
         "restoration" : false,
         "type" : "ASEStagingSource",
         "virtual" : false,
         "postScript" : null,
         "config" : "ASE_SI_CONFIG-109",
         "status" : "DEFAULT",
         "description" : null,
         "staging" : true,
         "mountBase" : "/u01/app/toolkit/564d870b-e091-7339-5d98-e7cc4bdbfbcc-staging-60",
         "preScript" : null,
         "name" : "dx397l9vX98vvd6a9nWwn9_pubs3",
         "reference" : "ASE_STAGING_SOURCE-60",
         "namespace" : null,
         "linked" : false
      }
   ]
}
