{
   "job" : null,
   "overflow" : false,
   "result" : [
      {
         "rmanChannels" : 2,
         "virtual" : false,
         "name" : "orcl",
         "container" : "ORACLE_DB_CONTAINER-316",
         "linked" : true,
         "encryptedLinkingEnabled" : false,
         "config" : "ORACLE_SINGLE_CONFIG-38",
         "numberOfConnections" : 1,
         "description" : null,
         "externalFilePath" : null,
         "backupLevelEnabled" : false,
         "bandwidthLimit" : 0,
         "status" : "DEFAULT",
         "type" : "OracleLinkedSource",
         "filesPerSet" : 5,
         "operations" : {
            "type" : "LinkedSourceOperations",
            "preSync" : [],
            "postSync" : []
         },
         "compressedLinkingEnabled" : true,
         "restoration" : false,
         "checkLogical" : false,
         "namespace" : null,
         "runtime" : {
            "racEnabled" : null,
            "archivelogEnabled" : null,
            "databaseStats" : [],
            "bctEnabled" : false,
            "type" : "OracleSourceRuntime",
            "status" : "UNKNOWN",
            "notAccessibleReason" : "Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection",
            "databaseMode" : null,
            "accessible" : false,
            "activeInstances" : [],
            "databaseSize" : 0,
            "enabled" : "ENABLED",
            "lastNonLoggedLocation" : null,
            "dnfsEnabled" : false,
            "databaseRole" : null
         },
         "reference" : "ORACLE_LINKED_SOURCE-73",
         "staging" : false
      },
      {
         "bandwidthLimit" : 0,
         "type" : "OracleLinkedSource",
         "status" : "DEFAULT",
         "backupLevelEnabled" : false,
         "externalFilePath" : "",
         "staging" : false,
         "runtime" : {
            "databaseRole" : null,
            "lastNonLoggedLocation" : null,
            "databaseSize" : 0,
            "enabled" : "ENABLED",
            "activeInstances" : [],
            "accessible" : false,
            "databaseMode" : null,
            "status" : "UNKNOWN",
            "type" : "OraclePDBSourceRuntime",
            "notAccessibleReason" : "Environment monitoring job timed out.",
            "databaseStats" : []
         },
         "reference" : "ORACLE_LINKED_SOURCE-32",
         "namespace" : null,
         "checkLogical" : false,
         "compressedLinkingEnabled" : true,
         "restoration" : false,
         "operations" : {
            "type" : "LinkedSourceOperations",
            "preSync" : [],
            "postSync" : []
         },
         "filesPerSet" : 5,
         "name" : "PDB",
         "virtual" : false,
         "rmanChannels" : 2,
         "description" : null,
         "numberOfConnections" : 1,
         "config" : "ORACLE_PDB_CONFIG-54",
         "encryptedLinkingEnabled" : false,
         "linked" : true,
         "container" : "ORACLE_DB_CONTAINER-138"
      },
      {
         "operations" : {
            "type" : "LinkedSourceOperations",
            "postSync" : [],
            "preSync" : []
         },
         "filesPerSet" : 5,
         "restoration" : false,
         "compressedLinkingEnabled" : false,
         "checkLogical" : false,
         "namespace" : null,
         "runtime" : {
            "databaseSize" : 0,
            "enabled" : "ENABLED",
            "lastNonLoggedLocation" : null,
            "dnfsEnabled" : false,
            "databaseRole" : null,
            "racEnabled" : null,
            "databaseStats" : [],
            "archivelogEnabled" : null,
            "type" : "OracleSourceRuntime",
            "bctEnabled" : false,
            "status" : "UNKNOWN",
            "notAccessibleReason" : "Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection",
            "databaseMode" : null,
            "accessible" : false,
            "activeInstances" : []
         },
         "reference" : "ORACLE_LINKED_SOURCE-70",
         "staging" : false,
         "externalFilePath" : null,
         "backupLevelEnabled" : false,
         "bandwidthLimit" : 0,
         "type" : "OracleLinkedSource",
         "status" : "DEFAULT",
         "container" : "ORACLE_DB_CONTAINER-305",
         "encryptedLinkingEnabled" : false,
         "linked" : true,
         "config" : "ORACLE_SINGLE_CONFIG-56",
         "numberOfConnections" : 1,
         "description" : null,
         "rmanChannels" : 2,
         "virtual" : false,
         "name" : "targetcon"
      },
      {
         "operations" : {
            "type" : "LinkedSourceOperations",
            "postSync" : [],
            "preSync" : []
         },
         "filesPerSet" : 5,
         "restoration" : false,
         "compressedLinkingEnabled" : true,
         "checkLogical" : false,
         "namespace" : null,
         "reference" : "ORACLE_LINKED_SOURCE-5",
         "runtime" : {
            "racEnabled" : null,
            "archivelogEnabled" : null,
            "databaseStats" : [],
            "type" : "OracleSourceRuntime",
            "bctEnabled" : false,
            "status" : "UNKNOWN",
            "notAccessibleReason" : "Object is not available for monitoring",
            "accessible" : false,
            "databaseMode" : null,
            "activeInstances" : [],
            "databaseSize" : 0,
            "enabled" : "DISABLED",
            "lastNonLoggedLocation" : null,
            "dnfsEnabled" : false,
            "databaseRole" : null
         },
         "staging" : false,
         "backupLevelEnabled" : false,
         "externalFilePath" : "",
         "status" : "DEFAULT",
         "bandwidthLimit" : 0,
         "type" : "OracleLinkedSource",
         "container" : "ORACLE_DB_CONTAINER-29",
         "linked" : true,
         "encryptedLinkingEnabled" : false,
         "config" : "ORACLE_RAC_CONFIG-10",
         "numberOfConnections" : 1,
         "description" : null,
         "rmanChannels" : 2,
         "virtual" : false,
         "name" : "racdba"
      },
      {
         "numberOfConnections" : 1,
         "description" : null,
         "container" : "ORACLE_DB_CONTAINER-137",
         "linked" : true,
         "encryptedLinkingEnabled" : false,
         "config" : "ORACLE_SINGLE_CONFIG-53",
         "virtual" : false,
         "name" : "singpdb",
         "rmanChannels" : 2,
         "namespace" : null,
         "runtime" : {
            "lastNonLoggedLocation" : null,
            "enabled" : "DISABLED",
            "databaseSize" : 0,
            "databaseRole" : null,
            "dnfsEnabled" : false,
            "notAccessibleReason" : "Object is not available for monitoring",
            "status" : "UNKNOWN",
            "bctEnabled" : false,
            "type" : "OracleSourceRuntime",
            "archivelogEnabled" : null,
            "databaseStats" : [],
            "racEnabled" : null,
            "activeInstances" : [],
            "databaseMode" : null,
            "accessible" : false
         },
         "reference" : "ORACLE_LINKED_SOURCE-31",
         "staging" : false,
         "operations" : {
            "type" : "LinkedSourceOperations",
            "postSync" : [],
            "preSync" : []
         },
         "filesPerSet" : 5,
         "compressedLinkingEnabled" : false,
         "restoration" : false,
         "checkLogical" : false,
         "externalFilePath" : null,
         "backupLevelEnabled" : false,
         "type" : "OracleLinkedSource",
         "bandwidthLimit" : 0,
         "status" : "DEFAULT"
      },
      {
         "container" : "ORACLE_DB_CONTAINER-249",
         "encryptedLinkingEnabled" : false,
         "linked" : true,
         "config" : "ORACLE_SINGLE_CONFIG-106",
         "numberOfConnections" : 1,
         "description" : null,
         "rmanChannels" : 2,
         "virtual" : false,
         "name" : "unic",
         "filesPerSet" : 5,
         "operations" : {
            "type" : "LinkedSourceOperations",
            "postSync" : [],
            "preSync" : []
         },
         "compressedLinkingEnabled" : true,
         "restoration" : false,
         "checkLogical" : false,
         "namespace" : null,
         "runtime" : {
            "databaseSize" : 0,
            "enabled" : "DISABLED",
            "lastNonLoggedLocation" : null,
            "dnfsEnabled" : false,
            "databaseRole" : null,
            "racEnabled" : null,
            "databaseStats" : [],
            "archivelogEnabled" : null,
            "bctEnabled" : false,
            "status" : "UNKNOWN",
            "type" : "OracleSourceRuntime",
            "notAccessibleReason" : "Object is not available for monitoring",
            "databaseMode" : null,
            "accessible" : false,
            "activeInstances" : []
         },
         "reference" : "ORACLE_LINKED_SOURCE-47",
         "staging" : false,
         "externalFilePath" : "",
         "backupLevelEnabled" : false,
         "bandwidthLimit" : 0,
         "type" : "OracleLinkedSource",
         "status" : "DEFAULT"
      },
      {
         "namespace" : null,
         "mountBase" : "/mnt/provision",
         "runtime" : {
            "notAccessibleReason" : "Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection",
            "status" : "INACTIVE",
            "bctEnabled" : false,
            "type" : "OracleSourceRuntime",
            "databaseStats" : [],
            "archivelogEnabled" : null,
            "racEnabled" : null,
            "activeInstances" : [],
            "accessible" : false,
            "databaseMode" : null,
            "lastNonLoggedLocation" : null,
            "enabled" : "ENABLED",
            "databaseSize" : 0,
            "databaseRole" : null,
            "dnfsEnabled" : false
         },
         "reference" : "ORACLE_VIRTUAL_SOURCE-112",
         "staging" : false,
         "operations" : {
            "postRollback" : [],
            "preStop" : [],
            "postRefresh" : [],
            "type" : "VirtualSourceOperations",
            "postStop" : [],
            "preStart" : [],
            "configureClone" : [],
            "preRefresh" : [],
            "postSnapshot" : [],
            "postStart" : [],
            "preRollback" : [],
            "preSnapshot" : []
         },
         "restoration" : false,
         "redoLogSizeInMB" : 100,
         "configParams" : {
            "filesystemio_options" : "'setall'",
            "audit_sys_operations" : "FALSE",
            "audit_trail" : "'NONE'",
            "compatible" : "'12.1.0.2.0'",
            "remote_login_passwordfile" : "'EXCLUSIVE'",
            "_omf" : "'ENABLED'",
            "log_archive_dest_1" : "'location=/mnt/provision/si4rac/archive/ MANDATORY'",
            "processes" : "500",
            "memory_target" : "792723456",
            "open_cursors" : "300"
         },
         "configTemplate" : null,
         "type" : "OracleVirtualSource",
         "status" : "DEFAULT",
         "archivelogMode" : true,
         "allowAutoVDBRestartOnHostReboot" : true,
         "description" : null,
         "container" : "ORACLE_DB_CONTAINER-306",
         "linked" : false,
         "config" : "ORACLE_SINGLE_CONFIG-137",
         "virtual" : true,
         "customEnvVars" : [],
         "redoLogGroups" : 3,
         "manualProvisioning" : null,
         "fileMappingRules" : null,
         "name" : "si4rac",
         "nodeListenerList" : []
      },
      {
         "staging" : false,
         "mountBase" : "/mnt/provision",
         "runtime" : {
            "status" : "INACTIVE",
            "bctEnabled" : false,
            "type" : "OracleSourceRuntime",
            "notAccessibleReason" : "Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection",
            "racEnabled" : null,
            "archivelogEnabled" : null,
            "databaseStats" : [],
            "activeInstances" : [],
            "accessible" : false,
            "databaseMode" : null,
            "lastNonLoggedLocation" : null,
            "databaseSize" : 0,
            "enabled" : "ENABLED",
            "databaseRole" : null,
            "dnfsEnabled" : false
         },
         "reference" : "ORACLE_VIRTUAL_SOURCE-116",
         "namespace" : null,
         "redoLogSizeInMB" : 100,
         "restoration" : false,
         "operations" : {
            "configureClone" : [],
            "preStart" : [],
            "postStop" : [],
            "type" : "VirtualSourceOperations",
            "preSnapshot" : [],
            "preRollback" : [],
            "postSnapshot" : [],
            "postStart" : [],
            "preRefresh" : [],
            "postRollback" : [],
            "postRefresh" : [],
            "preStop" : []
         },
         "configTemplate" : null,
         "type" : "OracleVirtualSource",
         "status" : "DEFAULT",
         "configParams" : {
            "_omf" : "'ENABLED'",
            "remote_login_passwordfile" : "'EXCLUSIVE'",
            "audit_sys_operations" : "FALSE",
            "compatible" : "'11.2.0.4.0'",
            "audit_trail" : "'NONE'",
            "sga_target" : "738197504",
            "filesystemio_options" : "'setall'",
            "open_cursors" : "300",
            "processes" : "700",
            "pga_aggregate_target" : "245366784",
            "log_archive_dest_1" : "'location=/mnt/provision/autotest/archive/ MANDATORY'"
         },
         "allowAutoVDBRestartOnHostReboot" : false,
         "description" : null,
         "archivelogMode" : true,
         "config" : "ORACLE_SINGLE_CONFIG-141",
         "linked" : false,
         "container" : "ORACLE_DB_CONTAINER-317",
         "manualProvisioning" : null,
         "name" : "autotest",
         "fileMappingRules" : null,
         "virtual" : true,
         "customEnvVars" : [],
         "redoLogGroups" : 3,
         "nodeListenerList" : []
      },
      {
         "staging" : false,
         "reference" : "ORACLE_VIRTUAL_SOURCE-110",
         "runtime" : {
            "activeInstances" : [],
            "databaseMode" : null,
            "accessible" : false,
            "notAccessibleReason" : "Cannot connect to database due to: Exception occurred while getting connection: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection",
            "status" : "UNKNOWN",
            "type" : "OraclePDBSourceRuntime",
            "databaseStats" : [],
            "databaseRole" : null,
            "lastNonLoggedLocation" : null,
            "enabled" : "ENABLED",
            "databaseSize" : 0
         },
         "mountBase" : "/mnt/provision",
         "namespace" : null,
         "redoLogSizeInMB" : 100,
         "restoration" : false,
         "operations" : {
            "preStop" : [],
            "postRefresh" : [],
            "postRollback" : [],
            "preRollback" : [],
            "preSnapshot" : [],
            "preRefresh" : [],
            "postStart" : [],
            "postSnapshot" : [],
            "configureClone" : [],
            "preStart" : [],
            "postStop" : [],
            "type" : "VirtualSourceOperations"
         },
         "type" : "OracleVirtualSource",
         "configTemplate" : null,
         "status" : "DEFAULT",
         "configParams" : {
            "enable_pluggable_database" : "TRUE",
            "db_domain" : "''",
            "open_cursors" : "300",
            "pga_aggregate_target" : "398458880",
            "processes" : "300",
            "diagnostic_dest" : "'/u01/app/oracle'",
            "audit_file_dest" : "'/u01/app/oracle/admin/targetcon/adump'",
            "dispatchers" : "'(PROTOCOL=TCP) (SERVICE=targetconXDB)'",
            "remote_login_passwordfile" : "'EXCLUSIVE'",
            "audit_trail" : "'DB'",
            "sga_target" : "1207959552",
            "compatible" : "'12.1.0.2.0'"
         },
         "description" : null,
         "allowAutoVDBRestartOnHostReboot" : false,
         "archivelogMode" : true,
         "config" : "ORACLE_PDB_CONFIG-135",
         "linked" : false,
         "container" : "ORACLE_DB_CONTAINER-303",
         "name" : "vPDBtest",
         "manualProvisioning" : null,
         "fileMappingRules" : null,
         "customEnvVars" : [],
         "virtual" : true,
         "redoLogGroups" : 3,
         "nodeListenerList" : []
      },
      {
         "name" : "AdventureWorksLT2008R2",
         "virtual" : false,
         "encryptionKey" : null,
         "validatedSyncMode" : "NONE",
         "backupLocationUser" : null,
         "description" : null,
         "container" : "MSSQL_DB_CONTAINER-309",
         "backupLocationCredentials" : null,
         "config" : "MSSQL_SINGLE_CONFIG-23",
         "linked" : true,
         "externalFilePath" : null,
         "status" : "DEFAULT",
         "type" : "MSSqlLinkedSource",
         "sharedBackupLocation" : "\\\\172.16.180.133\\backups",
         "runtime" : {
            "accessible" : false,
            "type" : "MSSqlSourceRuntime",
            "status" : "UNKNOWN",
            "notAccessibleReason" : "Failed to connect to host 172.16.180.132 [172.16.180.132]",
            "databaseSize" : 0,
            "enabled" : "ENABLED"
         },
         "reference" : "MSSQL_LINKED_SOURCE-16",
         "namespace" : null,
         "staging" : false,
         "operations" : {
            "type" : "LinkedSourceOperations",
            "preSync" : [],
            "postSync" : []
         },
         "stagingSource" : "MSSQL_STAGING_SOURCE-16",
         "restoration" : false
      },
      {
         "restoration" : false,
         "staging" : true,
         "postScript" : null,
         "namespace" : null,
         "mountBase" : "C:\\Program Files\\Delphix\\DelphixConnector\\564d870b-e091-7339-5d98-e7cc4bdbfbcc-staging-309",
         "reference" : "MSSQL_STAGING_SOURCE-16",
         "runtime" : {
            "accessible" : false,
            "status" : "UNKNOWN",
            "type" : "MSSqlSourceRuntime",
            "notAccessibleReason" : "Failed to connect to host 172.16.180.132 [172.16.180.132]",
            "databaseSize" : 0,
            "enabled" : "ENABLED"
         },
         "status" : "DEFAULT",
         "type" : "MSSqlStagingSource",
         "preScript" : null,
         "linked" : false,
         "config" : "MSSQL_SINGLE_CONFIG-38",
         "container" : "MSSQL_DB_CONTAINER-309",
         "description" : null,
         "virtual" : false,
         "name" : "564d870b-e091-7339-5d98-e7cc4bdbfbcc-staging-309"
      },
      {
         "name" : "/u02/app/mysql/data",
         "virtual" : false,
         "config" : "MYSQL_SERVER_CONFIG-8",
         "linked" : true,
         "container" : "MYSQL_DB_CONTAINER-246",
         "description" : null,
         "status" : "DEFAULT",
         "type" : "MySQLLinkedSource",
         "configParams" : {},
         "restoration" : false,
         "operations" : {
            "type" : "LinkedSourceOperations",
            "postSync" : [],
            "preSync" : []
         },
         "stagingSource" : "MYSQL_STAGING_SOURCE-1",
         "staging" : false,
         "reference" : "MYSQL_LINKED_SOURCE-1",
         "runtime" : {
            "accessible" : false,
            "notAccessibleReason" : null,
            "status" : "UNKNOWN",
            "type" : "MySQLSourceRuntime",
            "enabled" : "DISABLED",
            "databaseSize" : 0
         },
         "namespace" : null
      },
      {
         "config" : "MYSQL_SERVER_CONFIG-9",
         "linked" : false,
         "container" : "MYSQL_DB_CONTAINER-246",
         "description" : null,
         "name" : "/u01/app/toolkit/564d870b-e091-7339-5d98-e7cc4bdbfbcc-staging-246/datafile",
         "virtual" : false,
         "restoration" : false,
         "staging" : true,
         "reference" : "MYSQL_STAGING_SOURCE-1",
         "mountBase" : "/u01/app/toolkit/564d870b-e091-7339-5d98-e7cc4bdbfbcc-staging-246",
         "runtime" : {
            "accessible" : false,
            "enabled" : "DISABLED",
            "databaseSize" : 0,
            "notAccessibleReason" : null,
            "status" : "UNKNOWN",
            "type" : "MySQLSourceRuntime"
         },
         "namespace" : null,
         "postScript" : null,
         "type" : "MySQLStagingSource",
         "status" : "DEFAULT",
         "preScript" : null
      },
      {
         "excludes" : [],
         "status" : "DEFAULT",
         "type" : "AppDataLinkedDirectSource",
         "restoration" : false,
         "parameters" : {},
         "operations" : {
            "type" : "LinkedSourceOperations",
            "preSync" : [],
            "postSync" : []
         },
         "staging" : false,
         "namespace" : null,
         "runtime" : {
            "type" : "AppDataSourceRuntime",
            "status" : "UNKNOWN",
            "notAccessibleReason" : null,
            "databaseSize" : 25594880,
            "enabled" : "DISABLED",
            "accessible" : true
         },
         "reference" : "APPDATA_LINKED_SOURCE-7",
         "virtual" : false,
         "name" : "TESTEBI",
         "linked" : true,
         "config" : "APPDATA_SOURCE_CONFIG-16",
         "container" : "APPDATA_CONTAINER-146",
         "followSymlinks" : [],
         "description" : null
      },
      {
         "operations" : {
            "configureClone" : [],
            "postStop" : [],
            "type" : "VirtualSourceOperations",
            "preStart" : [],
            "preRollback" : [],
            "preSnapshot" : [],
            "preRefresh" : [],
            "postSnapshot" : [],
            "postStart" : [],
            "postRollback" : [],
            "preStop" : [],
            "postRefresh" : []
         },
         "restoration" : false,
         "parameters" : {},
         "reference" : "APPDATA_VIRTUAL_SOURCE-6",
         "runtime" : {
            "databaseSize" : 25594880,
            "enabled" : "DISABLED",
            "type" : "AppDataSourceRuntime",
            "status" : "UNKNOWN",
            "notAccessibleReason" : null,
            "accessible" : true
         },
         "namespace" : null,
         "additionalMountPoints" : [],
         "staging" : false,
         "type" : "AppDataVirtualSource",
         "status" : "DEFAULT",
         "container" : "APPDATA_CONTAINER-149",
         "config" : "APPDATA_SOURCE_CONFIG-19",
         "linked" : false,
         "allowAutoVDBRestartOnHostReboot" : false,
         "description" : null,
         "name" : "autofs",
         "virtual" : true
      },
      {
         "name" : "Sybase dsource",
         "loadLocation" : null,
         "virtual" : false,
         "validatedSyncMode" : "ENABLED",
         "container" : "ASE_DB_CONTAINER-307",
         "config" : "ASE_SI_CONFIG-64",
         "linked" : true,
         "description" : null,
         "dumpCredentials" : null,
         "loadBackupPath" : "/u02/sybase_back",
         "externalFilePath" : null,
         "type" : "ASELinkedSource",
         "status" : "DEFAULT",
         "operations" : {
            "type" : "LinkedSourceOperations",
            "preSync" : [],
            "postSync" : []
         },
         "stagingSource" : "ASE_STAGING_SOURCE-66",
         "restoration" : false,
         "reference" : "ASE_LINKED_SOURCE-66",
         "runtime" : {
            "enabled" : "ENABLED",
            "databaseSize" : 0,
            "truncateLogOnCheckpoint" : null,
            "notAccessibleReason" : "Execution thread unexpectedly failed",
            "type" : "ASESourceRuntime",
            "status" : "UNKNOWN",
            "accessible" : false,
            "durabilityLevel" : null
         },
         "namespace" : null,
         "staging" : false
      },
      {
         "restoration" : false,
         "operations" : {
            "postRefresh" : [],
            "preStop" : [],
            "postRollback" : [],
            "postStart" : [],
            "postSnapshot" : [],
            "preRefresh" : [],
            "preSnapshot" : [],
            "preRollback" : [],
            "type" : "VirtualSourceOperations",
            "postStop" : [],
            "preStart" : [],
            "configureClone" : []
         },
         "staging" : false,
         "reference" : "ASE_VIRTUAL_SOURCE-47",
         "mountBase" : "/u01/app/toolkit/564d870b-e091-7339-5d98-e7cc4bdbfbcc-vdb-47",
         "runtime" : {
            "databaseSize" : 0,
            "enabled" : "ENABLED",
            "status" : "INACTIVE",
            "type" : "ASESourceRuntime",
            "notAccessibleReason" : "",
            "truncateLogOnCheckpoint" : false,
            "durabilityLevel" : "FULL",
            "accessible" : false
         },
         "namespace" : null,
         "type" : "ASEVirtualSource",
         "status" : "DEFAULT",
         "configParams" : null,
         "config" : "ASE_SI_CONFIG-124",
         "linked" : false,
         "container" : "ASE_DB_CONTAINER-320",
         "allowAutoVDBRestartOnHostReboot" : false,
         "description" : null,
         "name" : "testsys",
         "fileMappingRules" : null,
         "virtual" : true
      },
      {
         "staging" : false,
         "reference" : "ASE_VIRTUAL_SOURCE-46",
         "runtime" : {
            "notAccessibleReason" : null,
            "truncateLogOnCheckpoint" : false,
            "status" : "RUNNING",
            "type" : "ASESourceRuntime",
            "accessible" : true,
            "durabilityLevel" : "FULL",
            "enabled" : "ENABLED",
            "databaseSize" : 314572800
         },
         "mountBase" : "/u01/app/toolkit/564d870b-e091-7339-5d98-e7cc4bdbfbcc-vdb-46",
         "namespace" : null,
         "restoration" : false,
         "operations" : {
            "postStop" : [],
            "type" : "VirtualSourceOperations",
            "preStart" : [],
            "configureClone" : [],
            "preRefresh" : [],
            "postStart" : [],
            "postSnapshot" : [],
            "preRollback" : [],
            "preSnapshot" : [],
            "postRollback" : [],
            "preStop" : [],
            "postRefresh" : []
         },
         "status" : "DEFAULT",
         "type" : "ASEVirtualSource",
         "configParams" : null,
         "description" : null,
         "allowAutoVDBRestartOnHostReboot" : false,
         "config" : "ASE_SI_CONFIG-123",
         "linked" : false,
         "container" : "ASE_DB_CONTAINER-314",
         "fileMappingRules" : null,
         "name" : "tests",
         "virtual" : true
      },
      {
         "container" : "ASE_DB_CONTAINER-307",
         "config" : "ASE_SI_CONFIG-121",
         "linked" : false,
         "description" : null,
         "name" : "dxv363l2I9vdf72ba4bvz7_pubs3",
         "virtual" : false,
         "restoration" : false,
         "runtime" : {
            "databaseSize" : 7340032,
            "enabled" : "ENABLED",
            "durabilityLevel" : "FULL",
            "accessible" : true,
            "status" : "RUNNING",
            "type" : "ASESourceRuntime",
            "truncateLogOnCheckpoint" : false,
            "notAccessibleReason" : null
         },
         "mountBase" : "/u01/app/toolkit/564d870b-e091-7339-5d98-e7cc4bdbfbcc-staging-66",
         "reference" : "ASE_STAGING_SOURCE-66",
         "postScript" : null,
         "namespace" : null,
         "staging" : true,
         "preScript" : null,
         "status" : "DEFAULT",
         "type" : "ASEStagingSource"
      }
   ],
   "total" : 19,
   "type" : "ListResult",
   "status" : "OK",
   "action" : null
}
